version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10.15.1
commands:
  yarn_install:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
jobs:
  build:
    executor: node
    working_directory: ~/repo
    steps:
      - checkout
      - yarn_install
      - run: yarn run test:unit:ci
